---

- hosts: 127.0.0.1
  connection: local

  vars:
    gcs_builder_username: 'builder'
    gcs_source_dir: '/home/builder/src'
    gcs_python_version: 3
    # gcs_svn_branch_url: 'https://svn.osgeo.org/grass/grass/branches/releasebranch_7_6/'
    gcs_svn_branch_url: 'https://svn.osgeo.org/grass/grass/trunk/'

  roles:
    - role: pmav99.compile_grass
      become: true
