---

- hosts: 127.0.0.1
  connection: local

  vars:
    gcs_builder_username: 'builder'
    # gcs_svn_branch: 'https://svn.osgeo.org/grass/grass/branches/releasebranch_7_6/'
    gcs_svn_branch: 'https://svn.osgeo.org/grass/grass/trunk/'
    gcs_python_version: 3

  roles:
    - role: pmav99.compile_grass
      become: true
