---
# tasks file for compile_grass

- name: 'Copy the GRASS gui launcher script'
  copy:
    src: 'run_gui.sh'
    dest: '{{ gcs_source_dir }}/grass/run_gui.sh'
    owner: '{{ gcs_account_username }}'
    group: '{{ gcs_account_username }}'
    mode: '0744'
  become_user: '{{ gcs_account_username }}'
  become: true

- name: 'Copy the test launcher script'
  copy:
    src: 'run_tests.sh'
    dest: '{{ gcs_source_dir }}/grass/run_tests.sh'
    owner: '{{ gcs_account_username }}'
    group: '{{ gcs_account_username }}'
    mode: '0744'
  become_user: '{{ gcs_account_username }}'
  become: true


- name: 'Create the grass configuration script'
  template:
    src: 'do_configure.sh.j2'
    dest: '{{ gcs_source_dir }}/grass/do_configure.sh'
    owner: '{{ gcs_account_username }}'
    group: '{{ gcs_account_username }}'
    mode: '0744'
  become_user: '{{ gcs_account_username }}'
  become: true

- name: 'Create the grass compilation script'
  template:
    src: 'do_compile.sh.j2'
    dest: '{{ gcs_source_dir }}/grass/do_compile.sh'
    owner: '{{ gcs_account_username }}'
    group: '{{ gcs_account_username }}'
    mode: '0744'
  become_user: '{{ gcs_account_username }}'
  become: true

- name: 'Configure GRASS from source'
  command: '{{ gcs_source_dir }}/grass/do_configure.sh'
  changed_when: false
  become_user: '{{ gcs_account_username }}'
  become: true

- name: 'Cleanup output of previous compilations 1/2'
  command: 'make cleandistdirs'
  args:
    chdir: '{{ gcs_source_dir }}/grass/'
  changed_when: false
  become: true

- name: 'Cleanup output of previous compilations 2/2'
  file:
    state: absent
    path: '{{ gcs_source_dir }}/grass/compilation_output.txt'
  changed_when: false
  become: true

- name: 'Compile GRASS from source'
  tags:
    - skip_ansible_lint
  command: '{{ gcs_source_dir }}/grass/do_compile.sh'
  args:
    chdir: '{{ gcs_source_dir }}/grass/'
    creates: 'bin.x86_64-pc-linux-gnu/grass*'
  # We need to ignore errors, because on trunk some grass module might be broken.
  # Nevertheless, the grass binary should usually still be in a working state
  changed_when: false
  ignore_errors: true
  # Compilation should be done as a normal user
  become_user: '{{ gcs_account_username }}'
  become: true

- name: 'Ensure that grass was actually compiled.'
  stat:
    path: '{{ gcs_source_dir }}/grass/bin.x86_64-pc-linux-gnu/grass*'
  become: true
