---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  vars:
    gsi_builder_username: 'builder'

  roles:
    - role: pmav99.compile_grass
