---
- name: Converge
  hosts: all
  become: true

  vars:
    gcs_account_username: 'builder'
    gcs_python_version: "{{ lookup('env', 'TESTED_PYTHON_VERSION') }}"
    gcs_source_dir: '/usr/local/src/'

  pre_tasks:
    - name: 'Update apt cache'
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - role: "{{ lookup('env', 'FULL_ROLE_NAME') or 'compile_grass' }}"
