---
- name: Converge
  hosts: all
  become: true

  vars:
    gcs_account_username: 'builder'
    gcs_python_version: "{{ lookup('env', 'TESTED_PYTHON_VERSION') }}"
    gcs_source_dir: '/usr/local/src/'

    gcs_blas_support: true
    gcs_bzip2_support: true
    gcs_cxx_support: true
    gcs_cairo_support: true
    gcs_fftw_support: true
    gcs_freetype_support: true
    gcs_gdal_support: true
    gcs_geos_support: true
    gcs_lapack_support: true
    gcs_liblas_support: true
    gcs_mysql_support: true
    gcs_netcdf_support: true
    gcs_nls_support: true
    gcs_odbc_support: true
    gcs_opencl_support: false
    gcs_opengl_support: true
    gcs_openmp_support: true
    gcs_pdal_support: true
    gcs_png_support: true
    gcs_pthread_support: true
    gcs_postgres_support: true
    gcs_readline_support: true    # This is true by default, but why?
    gcs_regex_support: true
    gcs_sqlite_support: true
    gcs_tiff_support: true
    gcs_w11_support: true
    gcs_zstd_support: true

    gcs_run_tests: true

  pre_tasks:
    - name: 'Update apt cache'
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - role: "{{ lookup('env', 'FULL_ROLE_NAME') or 'compile_grass' }}"
