---
- name: Converge
  hosts: all
  become: true

  vars:
    gsi_builder_username: 'builder'
    gsi_setup_xpra: true

  pre_tasks:
    - name: 'Update apt cache'
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: "{{ lookup('env', 'FULL_ROLE_NAME') or 'compile_grass' }}"
